apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
spec:
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      imagePullSecrets:
      - name: ecr
      containers:
      - name: manager
        image: $awsEcrRegistry/$repositoryName:$imgTag
        resources:
          requests:
            memory: 256Mi
            cpu: 500m
          limits:
            memory: 256Mi
            cpu: 500m
        env:
          - name: ASPNETCORE_URLS
            value: http://*:$appPort
          - name: ConnectionStrings__DefaultConnection
            value: $connectionString
          - name: Aws__PoolId
            value: $poolId
          - name: Aws__PoolClientId
            value: $poolClientId
        ports:
        - containerPort: $appPort
          name: manager
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: manager-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: manager
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
---
apiVersion: v1
kind: Service
metadata:
  name: manager-svs
spec:
  type: LoadBalancer
  ports:
  - port: $appPort
    targetPort: $appPort
  selector:
    app: manager